#include<stdio.h>
 int main()
 {
  int n,m,t,a[100][2],b[100][2],c[100][2]={0},i,j,max;
  scanf("%d%d%d",&n,&m,&t);
  for(i=1;i<=n;i++)
      scanf("%d%d",&a[i][0],&a[i][1]);
  for(i=1;i<=m;i++)
      scanf("%d%d",&b[i][0],&b[i][1]);
  max=a[n][1];
  if(b[m][1]>max)
     max=b[m][1];
  for(i=0;i<=max;i++)
  {
  	c[i][1]=i;
  	for(j=1;j<=n;j++)
    {
    	if(a[j][1]==i)
    	{
    		c[i][0]=a[j][0];
    		break;
		}
	}
  }
 if(t==0)
 {
  	for(i=0;i<=max;i++)
   {
  	for(j=1;j<=m;j++)
    {
    	if(b[j][1]==i)
    	{
    		c[i][0]+=b[j][0];
    		break;
		}
	}
   }
 }
 else
 {
 	for(i=0;i<=max;i++)
   {
  	for(j=1;j<=m;j++)
    {
    	if(b[j][1]==i)
    	{
    		c[i][0]-=b[j][0];
    		break;
		}
	}
   }
 }
  if(c[0][0]!=0)
    printf("%d",c[0][0]);
  if(c[1][0]>0)
  {
  	if(c[1][0]==1)
	  printf("+x",c[1][0]);
	else
	  printf("+%dx",c[1][0]);
  }
  else if(c[1][0]<0)
  {
  	if(c[1][0]==-1)
	  printf("-x",c[1][0]);
	else
	  printf("%dx",c[1][0]);
  }
  for(i=2;i<=max;i++)
   {
   	if(c[i][0]>0)
   	{
   		if(c[i][0]==1)
	       printf("+x^%d",c[i][1]);
	    else
	       printf("+%dx^%d",c[i][0],c[i][1]); 
	}
    else if(c[i][1]<0)
    {
    	if(c[i][0]==-1)
	       printf("-x^%d",c[i][1]);
	    else
	       printf("%dx^%d",c[i][0],c[i][1]);//发现当输入-2、-3之类的负数时，结果都会当成-1处理，各位大佬可以帮忙看看问题在哪。。。 
	}
   }
return 0;
}
