IO244		EQU	0230H		;244(16位)片选
IO273		EQU	0230H		;273(16位)片选

_STACK		SEGMENT	STACK	
		DW	100 DUP(?)	
_STACK		ENDS		
			
_DATA		SEGMENT	WORD PUBLIC 'DATA'
_DATA		ENDS		
			
CODE		SEGMENT		
START		PROC	NEAR	
		ASSUME	CS:CODE, DS:_DATA, SS:_STACK
		MOV	AX,_DATA	
        	MOV     DS,AX
		MOV	DX,IO244
		IN	AX,DX		;读取开关数据(16位，K0 K7 K6 K5 K4 K3 K2 K1 K7 K6 K5 K4 K3 K2 K1 K0)
		MOV	DX,IO273
		OUT	DX,AX
		CALL	Delay
		CALL	Delay
		CALL	Delay
		CALL	Delay
		CALL	Delay
		CALL	Delay
;		MOV	DX,IO273
		MOV	AX,0FFFEH
START1:		OUT	DX,AX
		CALL	Delay
		TEST	AX,8000H
		JZ	START
		ROL	AX,1
		JMP	START1

Delay		PROC	NEAR		;延时
Delay1:		XOR	CX,CX
		LOOP	$
		RET
Delay		ENDP
		
START		ENDP		
CODE		ENDS		

		END	START
