CREATE DATABASE xjgl;

USE DATABASE xjgl;

CREATE TABLE Student(Sno CHAR(9),Sname CHAR(20),Ssex CHAR(2),Sage INT,Sdept CHAR(20));
CREATE TABLE Course(Cno CHAR(4),Cname CHAR(40),Cpno CHAR(4),Ccredit INT);
CREATE TABLE SC(Sno CHAR(9),Cno CHAR(4),Grade INT);

DROP TABLE Student;

ALTER TABLE Student ADD birthdate DATE;
ALTER TABLE Student ADD PRIMARY KEY(Sno);
ALTER TABLE Student ADD UNIQUE(Sname);

CREATE TABLE Student(Sno CHAR(9) PRIMARY KEY,Sname CHAR(20) UNIQUE,Ssex CHAR(2),Sage SMALLINT,Sdept CHAR(20));
CREATE TABLE Course(Cno CHAR(4) PRIMARY KEY,Cname CHAR(40) NOT NULL,Cpno CHAR(4),Ccredit INT,FOREIGN KEY(Cpno) REFERENCES Course(Cno));
CREATE TABLE SC(Sno CHAR(9),Cno CHAR(4),Grade INT,PRIMARY KEY(Sno,Cno),FOREIGN KEY(Sno)REFERENCES Student(Sno),FOREIGN KEY(Cno)REFERENCES Course(Cno));

CREATE UNIQUE INDEX Stusno ON Student(Sno);
CREATE UNIQUE INDEX Coucno ON Course(Cno);
CREATE UNIQUE INDEX SCno ON SC(Sno ASC,Cno DESC);

DROP INDEX Stusno ON Student;

INSERT INTO Student VALUES('201215121','李勇','男',20,'CS');
INSERT INTO Student VALUES('201215122','刘晨','女',19,'CS');
INSERT INTO Student VALUES('201215123','王敏','女',18,'MA');
INSERT INTO Student VALUES('201215124','张立','男',19,'IS');
INSERT INTO COURSE VALUES('1','数据库','5',4);
INSERT INTO COURSE VALUES('3','信息系统','1',4);
INSERT INTO COURSE VALUES('4','操作系统','6',3);
INSERT INTO COURSE VALUES('5','数据结构','7',4);
INSERT INTO COURSE VALUES('7','PASCAL语言','6',4);
INSERT INTO SC VALUES('201215121','1',92);
INSERT INTO SC VALUES('201215121','2',85);
INSERT INTO SC VALUES('201215121','3',88);
INSERT INTO SC VALUES('201215122','2',90);
INSERT INTO SC VALUES('201215122','3',80);

INSERT INTO COURSE VALUES('2','数学',NULL,2);
INSERT INTO COURSE VALUES('6','数据处理',NULL,2);

insert into course(Cno,Cname,Ccredit) values ('2','数学',2);
insert into course(Cno,Cname,Ccredit) values ('6','数据处理',2);

UPDATE Student SET Sage=Sage+1;

UPDATE Course SET Cpno='1' WHERE Cno='6';

DELETE FROM SC WHERE Sno='201215121' AND Cno='1';
DELETE FROM SC;

SELECT * FROM Student;
SELECT * FROM Sc;
SELECT * FROM Course;
SELECT Sno,Sname,Sage FROM Student;
SELECT Sname FROM Student WHERE Sdept='cs';
SELECT Sname,Sage FROM Student WHERE Sage<20;

SELECT Sname,2021-Sage FROM Student;

SELECT Sname,'Year of birth:',2014-Sage FROM Student;

SELECT DISTINCT Sno FROM SC;
SELECT ALL Sno FROM SC;

SELECT* FROM Student WHERE Sage BETWEEN 20 AND 21;
SELECT * FROM Student WHERE Sdept IN('CS','IS');
SELECT * FROM Student WHERE Sname LIKE '刘%';
SELECT * FROM Student WHERE Sname LIKE '刘_';

SELECT* FROM Student ORDER BY Sdept,Sage DESC;
SELECT COUNT(*) FROM Student;
SELECT COUNT(DISTINCT Sno) FROM SC;
SELECT AVG(Sage) FROM Student;
SELECT SUM(Ccredit) FROM Course;
SELECT Sno FROM SC GROUP BY SNO HAVING COUNT(*)>=3;

SELECT Student.Sno,Sname FROM Student,SC WHERE Student.Sno=SC.Sno AND SC.Cno='2';

SELECT FIRST.Cno,SECOND.Cpno FROM Course FIRST,Course SECOND WHERE FIRST.Cpno=SECOND.Cno;
SELECT* FROM Student LEFT OUTER JOIN SC ON(Student.Sno=SC.Sno);
SELECT* FROM Course RIGHT OUTER JOIN SC ON(Course.Cno=SC.Cno);
SELECT* FROM Course JOIN SC ON(Course.Cno=SC.Cno);

SELECT Sname FROM Student WHERE EXISTS(SELECT* FROM SC WHERE Sno=Student.Sno AND Cno='1');

CREATE VIEW V1 AS SELECT SC.Sno,Sname FROM Student,SC WHERE Sdept='IS' AND SC.Cno='1' AND Student.Sno=SC.Sno;
CREATE VIEW V2 AS SELECT Sname FROM V1;

DROP VIEW V2;

SELECT Sname FROM V1 WHERE Sname LIKE '李_';